import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [myip, setMyip] = useState();

  async function webW() {
    const web = await fetch("http://ip-api.com/json/", {
      method: "GET",
    });

    setMyip((await web.json()).query);
  }
  useEffect(() => {
    webW();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Meu IP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Seu Ip é: {myip}</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
